import { Meeting } from "@/types";

export const mockMeetings: Meeting[] = [
    {
        id: "1",
        title: "Executive Board Monthly Review",
        description: "Monthly review of all committee activities and strategic objectives.",
        location: "APPNA Headquarters, Chicago",
        scheduled_at: "2026-03-20T14:00:00Z",
        duration_minutes: 90,
        status: "scheduled",
        committee_id: "1",
        committee_name: "Executive Board",
        scheduled_by_id: "user-1",
        scheduled_by_name: "Dr. Ahmed Khan",
        ai_summary: null,
        minutes: null,
        transcript: null,
        participants: [
            { id: "u1", name: "Dr. Ahmed Khan", email: "ahmed@appna.org", role: "President" },
            { id: "u2", name: "Dr. Sara Malik", email: "sara@appna.org", role: "Vice President" },
            { id: "u3", name: "Dr. Usman Riaz", email: "usman@appna.org", role: "Secretary" },
        ],
        documents: [],
        created_at: "2026-03-15T10:00:00Z",
    },
    {
        id: "2",
        title: "Health Policy Committee Briefing",
        description: "Review of current healthcare policy changes affecting APPNA members.",
        location: "Virtual — Zoom",
        scheduled_at: "2026-03-22T16:00:00Z",
        duration_minutes: 60,
        status: "scheduled",
        committee_id: "2",
        committee_name: "Health Policy",
        scheduled_by_id: "user-2",
        scheduled_by_name: "Dr. Sara Malik",
        ai_summary: null,
        minutes: null,
        transcript: null,
        participants: [
            { id: "u2", name: "Dr. Sara Malik", email: "sara@appna.org", role: "Chair" },
            { id: "u4", name: "Dr. Nadia Hussain", email: "nadia@appna.org", role: "Member" },
        ],
        documents: [],
        created_at: "2026-03-16T09:00:00Z",
    },
    {
        id: "3",
        title: "Annual Convention Planning Session",
        description: "Planning session for the upcoming APPNA annual convention.",
        location: "Marriott Chicago Downtown",
        scheduled_at: "2026-03-25T10:00:00Z",
        duration_minutes: 120,
        status: "scheduled",
        committee_id: "3",
        committee_name: "Convention",
        scheduled_by_id: "user-1",
        scheduled_by_name: "Dr. Ahmed Khan",
        ai_summary: null,
        minutes: null,
        transcript: null,
        participants: [
            { id: "u1", name: "Dr. Ahmed Khan", email: "ahmed@appna.org", role: "President" },
            { id: "u5", name: "Dr. Tariq Butt", email: "tariq@appna.org", role: "Chair" },
            { id: "u6", name: "Dr. Amna Sheikh", email: "amna@appna.org", role: "Member" },
            { id: "u7", name: "Dr. Bilal Chaudhry", email: "bilal@appna.org", role: "Member" },
        ],
        documents: [
            { id: "d1", name: "Convention_Proposal_2026.pdf", url: "#", size_bytes: 2048000, uploaded_at: "2026-03-16T12:00:00Z" },
        ],
        created_at: "2026-03-10T08:00:00Z",
    },
    {
        id: "4",
        title: "Finance Committee Q1 Review",
        description: "Review of Q1 financial statements and budget allocation.",
        location: "Virtual — Teams",
        scheduled_at: "2026-03-10T15:00:00Z",
        duration_minutes: 60,
        status: "completed",
        committee_id: "4",
        committee_name: "Finance",
        scheduled_by_id: "user-3",
        scheduled_by_name: "Dr. Usman Riaz",
        ai_summary: "The Finance Committee reviewed Q1 financial statements showing a 12% increase in membership dues collection compared to Q1 2025. Budget allocations for the annual convention were approved with a total budget of $450,000. The committee approved the purchase of new accounting software and discussed strategies for increasing endowment fund contributions.",
        minutes: "Meeting called to order at 3:05 PM by Dr. Usman Riaz.\n\n**Agenda Items:**\n1. Q1 Financial Statement Review\n2. Convention Budget Approval\n3. New Business\n\n**Key Decisions:**\n- Q1 statements approved unanimously\n- Convention budget of $450K approved\n- Accounting software purchase approved ($12,000)\n\nMeeting adjourned at 4:02 PM.",
        transcript: "Dr. Usman Riaz: Good afternoon everyone, let's get started with our Q1 review...",
        participants: [
            { id: "u3", name: "Dr. Usman Riaz", email: "usman@appna.org", role: "Chair" },
            { id: "u8", name: "Dr. Farida Qureshi", email: "farida@appna.org", role: "Treasurer" },
        ],
        documents: [
            { id: "d2", name: "Q1_Financial_Report.xlsx", url: "#", size_bytes: 512000, uploaded_at: "2026-03-10T14:00:00Z" },
            { id: "d3", name: "Budget_Proposal.pdf", url: "#", size_bytes: 1024000, uploaded_at: "2026-03-10T14:30:00Z" },
        ],
        created_at: "2026-03-05T08:00:00Z",
    },
    {
        id: "5",
        title: "Education Committee Strategic Planning",
        description: "Annual strategic planning session for education and training programs.",
        location: "APPNA HQ — Room 204",
        scheduled_at: "2026-03-05T13:00:00Z",
        duration_minutes: 180,
        status: "completed",
        committee_id: "5",
        committee_name: "Education",
        scheduled_by_id: "user-2",
        scheduled_by_name: "Dr. Sara Malik",
        ai_summary: "The Education Committee finalized the 2026 CME program calendar with 12 accredited sessions planned across major US cities. The committee approved funding for 5 medical student scholarships totaling $25,000. Plans for a new online learning platform were discussed and a vendor RFP process will begin in April.",
        minutes: "Strategic planning session for Education Committee FY2026...",
        transcript: null,
        participants: [
            { id: "u2", name: "Dr. Sara Malik", email: "sara@appna.org", role: "Chair" },
            { id: "u9", name: "Dr. Rehman Akhtar", email: "rehman@appna.org", role: "Vice Chair" },
            { id: "u10", name: "Dr. Zara Siddiqi", email: "zara@appna.org", role: "Member" },
        ],
        documents: [],
        created_at: "2026-02-25T08:00:00Z",
    },
    {
        id: "6",
        title: "Membership Drive Planning",
        description: "Planning session for Q2 membership drive campaign.",
        location: "Virtual — Zoom",
        scheduled_at: "2026-03-01T11:00:00Z",
        duration_minutes: 45,
        status: "cancelled",
        committee_id: "6",
        committee_name: "Membership",
        scheduled_by_id: "user-1",
        scheduled_by_name: "Dr. Ahmed Khan",
        ai_summary: null,
        minutes: null,
        transcript: null,
        cancelled_reason: "Key stakeholders unavailable due to conference conflict.",
        participants: [
            { id: "u1", name: "Dr. Ahmed Khan", email: "ahmed@appna.org", role: "President" },
        ],
        documents: [],
        created_at: "2026-02-20T08:00:00Z",
    },
];

export const mockCommittees = [
    { id: "1", name: "Executive Board" },
    { id: "2", name: "Health Policy" },
    { id: "3", name: "Convention" },
    { id: "4", name: "Finance" },
    { id: "5", name: "Education" },
    { id: "6", name: "Membership" },
    { id: "7", name: "International Medicine" },
    { id: "8", name: "Human Rights" },
];

export const mockParticipants = [
    { id: "u1", name: "Dr. Ahmed Khan", email: "ahmed@appna.org", role: "President" },
    { id: "u2", name: "Dr. Sara Malik", email: "sara@appna.org", role: "Vice President" },
    { id: "u3", name: "Dr. Usman Riaz", email: "usman@appna.org", role: "Secretary" },
    { id: "u4", name: "Dr. Nadia Hussain", email: "nadia@appna.org", role: "Member" },
    { id: "u5", name: "Dr. Tariq Butt", email: "tariq@appna.org", role: "Chair" },
    { id: "u6", name: "Dr. Amna Sheikh", email: "amna@appna.org", role: "Member" },
    { id: "u7", name: "Dr. Bilal Chaudhry", email: "bilal@appna.org", role: "Member" },
    { id: "u8", name: "Dr. Farida Qureshi", email: "farida@appna.org", role: "Treasurer" },
];
